#!/bin/sh

rm -r ACE1/ AP/ KLF/ LRIM1/ OVO/ RDL/
mkdir ACE1/ AP/ KLF/ LRIM1/ OVO/ RDL/

cd ACE1/
touch ACE1.fa
touch ACE1_Indels.fa
mkdir ACE1_Fimo
cd ACE1_Fimo/
mkdir streme
mkdir jaspar
cd ../..

cd AP/
touch AP.fa
touch AP_Indels.fa
mkdir AP_Fimo
cd AP_Fimo/
mkdir streme
mkdir jaspar
cd ../..

cd KLF/
touch KLF.fa
touch KLF_Indels.fa
mkdir KLF_Fimo
cd KLF_Fimo/
mkdir streme
mkdir jaspar
cd ../..

cd LRIM1/
touch LRIM1.fa
touch LRIM1_Indels.fa
mkdir LRIM1_Fimo
cd LRIM1_Fimo/
mkdir streme
mkdir jaspar
cd ../..

cd OVO/
touch OVO.fa
touch OVO_Indels.fa
mkdir OVO_Fimo
cd OVO_Fimo/
mkdir streme
mkdir jaspar
cd ../..

cd RDL/
touch RDL.fa
touch RDL_Indels.fa
mkdir RDL_Fimo
cd RDL_Fimo/
mkdir streme
mkdir jaspar
cd ../..