#define MEME_DIR "/home/petersjg/meme"
#define DATA_DIR "/home/petersjg/meme/share/meme-5.4.1" 
#define BIN_DIR "/home/petersjg/meme/bin" 
#define LIBEXEC_DIR "/home/petersjg/meme/libexec/meme-5.4.1" 
#define TEMP_DIR "" 
