#!/bin/bash

pushd ../
current_path=$(pwd)
streme=$(pwd)/motif_files/streme.txt
jaspar=$(pwd)/motif_files/JASPAR2020_CORE_insects_non-redundant_pfms_meme.txt
fimo_path=$(pwd)/fimo/meme-suite/meme-5.4.1/src
script_directory=$(pwd)/bin

while [ "$#" -gt "0" ]
do
    sequence=$(basename $1)
    
    filename="${sequence%.*}"
    global_path=$script_directory/$filename
    rm -r $script_directory/$filename
    mkdir $script_directory/$filename
    
    pushd $script_directory/$filename
    mkdir "streme"
    mkdir "jaspar"
    popd
    pushd $fimo_path

    ./fimo -oc $script_directory/$filename/streme $streme $1
    ./fimo -oc $script_directory/$filename/jaspar $jaspar $1

    popd
    shift
done

popd
unset streme
unset jaspar
unset filename
unset global_path
unset script_directory